[package]
name = "snake_bevy"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen="0.2.100"
bevy = "0.16.1"

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false
